-- leaaarrn-it — comprehensive shortcut seed data
-- Run AFTER schema.sql, in the Supabase Dashboard → SQL Editor → New query.
-- Idempotent: ON CONFLICT (name, app) updates the existing row, so re-running
-- refreshes data instead of erroring or duplicating.
--
-- NOTE: the `app` column is restricted by a CHECK constraint to these 9 values:
--   windows, macos, linux, chrome, firefox, vscode, excel, word, figma
-- To add more apps (PowerPoint, Slack, Photoshop, ...) see the bottom of this file.

insert into public.shortcuts (keys, name, description, platforms, category, difficulty, app)
values

-- ===========================================================================
-- WINDOWS (OS-level)
-- ===========================================================================
(array['ctrl','c'], 'Copy', 'Copy the selection to the clipboard.',
  '[{"name":"Copy","context":"Windows","os":"windows"}]', 'editing', 'beginner', 'windows'),
(array['ctrl','x'], 'Cut', 'Cut the selection to the clipboard.',
  '[{"name":"Cut","context":"Windows","os":"windows"}]', 'editing', 'beginner', 'windows'),
(array['ctrl','v'], 'Paste', 'Paste clipboard contents at the cursor.',
  '[{"name":"Paste","context":"Windows","os":"windows"}]', 'editing', 'beginner', 'windows'),
(array['ctrl','z'], 'Undo', 'Undo the last action.',
  '[{"name":"Undo","context":"Windows","os":"windows"}]', 'editing', 'beginner', 'windows'),
(array['ctrl','y'], 'Redo', 'Redo the previously undone action.',
  '[{"name":"Redo","context":"Windows","os":"windows"}]', 'editing', 'beginner', 'windows'),
(array['ctrl','a'], 'Select All', 'Select all items in the active view.',
  '[{"name":"Select All","context":"Windows","os":"windows"}]', 'editing', 'beginner', 'windows'),
(array['ctrl','s'], 'Save', 'Save the current file.',
  '[{"name":"Save","context":"Windows","os":"windows"}]', 'productivity', 'beginner', 'windows'),
(array['ctrl','p'], 'Print', 'Open the print dialog.',
  '[{"name":"Print","context":"Windows","os":"windows"}]', 'productivity', 'beginner', 'windows'),
(array['ctrl','f'], 'Find', 'Open the find bar to search the current document.',
  '[{"name":"Find","context":"Windows","os":"windows"}]', 'navigation', 'beginner', 'windows'),
(array['alt','tab'], 'Switch Apps', 'Cycle between open application windows.',
  '[{"name":"Switch Apps","context":"Windows","os":"windows"}]', 'navigation', 'beginner', 'windows'),
(array['alt','f4'], 'Close Window', 'Close the active window or app.',
  '[{"name":"Close Window","context":"Windows","os":"windows"}]', 'system', 'beginner', 'windows'),
(array['ctrl','shift','esc'], 'Open Task Manager', 'Open Task Manager directly.',
  '[{"name":"Task Manager","context":"Windows","os":"windows"}]', 'system', 'intermediate', 'windows'),
(array['meta','d'], 'Show Desktop', 'Minimize all windows to show the desktop.',
  '[{"name":"Show Desktop","context":"Windows key + D","os":"windows"}]', 'system', 'beginner', 'windows'),
(array['meta','e'], 'Open File Explorer', 'Launch File Explorer.',
  '[{"name":"File Explorer","context":"Windows key + E","os":"windows"}]', 'system', 'beginner', 'windows'),
(array['meta','l'], 'Lock PC', 'Lock the computer.',
  '[{"name":"Lock","context":"Windows key + L","os":"windows"}]', 'system', 'beginner', 'windows'),
(array['meta','r'], 'Run Dialog', 'Open the Run dialog.',
  '[{"name":"Run","context":"Windows key + R","os":"windows"}]', 'system', 'intermediate', 'windows'),
(array['meta','i'], 'Open Settings', 'Open Windows Settings.',
  '[{"name":"Settings","context":"Windows key + I","os":"windows"}]', 'system', 'beginner', 'windows'),
(array['meta','shift','s'], 'Screenshot Region', 'Capture a screen region with Snip & Sketch.',
  '[{"name":"Snip","context":"Windows key + Shift + S","os":"windows"}]', 'system', 'beginner', 'windows'),
(array['meta','arrowleft'], 'Snap Window Left', 'Snap the active window to the left half.',
  '[{"name":"Snap Left","context":"Windows key + Left","os":"windows"}]', 'system', 'intermediate', 'windows'),
(array['meta','arrowright'], 'Snap Window Right', 'Snap the active window to the right half.',
  '[{"name":"Snap Right","context":"Windows key + Right","os":"windows"}]', 'system', 'intermediate', 'windows'),
(array['meta','tab'], 'Task View', 'Open Task View to see windows and desktops.',
  '[{"name":"Task View","context":"Windows key + Tab","os":"windows"}]', 'navigation', 'intermediate', 'windows'),
(array['meta','ctrl','d'], 'New Virtual Desktop', 'Create a new virtual desktop.',
  '[{"name":"New Desktop","context":"Windows key + Ctrl + D","os":"windows"}]', 'system', 'advanced', 'windows'),
(array['meta','v'], 'Clipboard History', 'Open clipboard history.',
  '[{"name":"Clipboard History","context":"Windows key + V","os":"windows"}]', 'productivity', 'intermediate', 'windows'),
(array['f2'], 'Rename', 'Rename the selected file or folder.',
  '[{"name":"Rename","context":"Windows Explorer","os":"windows"}]', 'editing', 'beginner', 'windows'),

-- ===========================================================================
-- macOS (OS-level)
-- ===========================================================================
(array['meta','c'], 'Copy', 'Copy the selection to the clipboard.',
  '[{"name":"Copy","context":"macOS (Cmd+C)","os":"macos"}]', 'editing', 'beginner', 'macos'),
(array['meta','x'], 'Cut', 'Cut the selection to the clipboard.',
  '[{"name":"Cut","context":"macOS (Cmd+X)","os":"macos"}]', 'editing', 'beginner', 'macos'),
(array['meta','v'], 'Paste', 'Paste clipboard contents at the cursor.',
  '[{"name":"Paste","context":"macOS (Cmd+V)","os":"macos"}]', 'editing', 'beginner', 'macos'),
(array['meta','z'], 'Undo', 'Undo the last action.',
  '[{"name":"Undo","context":"macOS (Cmd+Z)","os":"macos"}]', 'editing', 'beginner', 'macos'),
(array['meta','shift','z'], 'Redo', 'Redo the previously undone action.',
  '[{"name":"Redo","context":"macOS (Cmd+Shift+Z)","os":"macos"}]', 'editing', 'beginner', 'macos'),
(array['meta','a'], 'Select All', 'Select all items in the active view.',
  '[{"name":"Select All","context":"macOS (Cmd+A)","os":"macos"}]', 'editing', 'beginner', 'macos'),
(array['meta','s'], 'Save', 'Save the current file.',
  '[{"name":"Save","context":"macOS (Cmd+S)","os":"macos"}]', 'productivity', 'beginner', 'macos'),
(array['meta','p'], 'Print', 'Open the print dialog.',
  '[{"name":"Print","context":"macOS (Cmd+P)","os":"macos"}]', 'productivity', 'beginner', 'macos'),
(array['meta','f'], 'Find', 'Open find to search the current document.',
  '[{"name":"Find","context":"macOS (Cmd+F)","os":"macos"}]', 'navigation', 'beginner', 'macos'),
(array['meta','space'], 'Spotlight Search', 'Open Spotlight to search the Mac.',
  '[{"name":"Spotlight","context":"macOS (Cmd+Space)","os":"macos"}]', 'navigation', 'beginner', 'macos'),
(array['meta','tab'], 'Switch Apps', 'Cycle between open applications.',
  '[{"name":"App Switcher","context":"macOS (Cmd+Tab)","os":"macos"}]', 'navigation', 'beginner', 'macos'),
(array['meta','q'], 'Quit App', 'Quit the active application.',
  '[{"name":"Quit","context":"macOS (Cmd+Q)","os":"macos"}]', 'system', 'beginner', 'macos'),
(array['meta','w'], 'Close Window', 'Close the active window.',
  '[{"name":"Close Window","context":"macOS (Cmd+W)","os":"macos"}]', 'system', 'beginner', 'macos'),
(array['meta','m'], 'Minimize Window', 'Minimize the active window to the Dock.',
  '[{"name":"Minimize","context":"macOS (Cmd+M)","os":"macos"}]', 'system', 'beginner', 'macos'),
(array['meta','ctrl','q'], 'Lock Screen', 'Lock the screen immediately.',
  '[{"name":"Lock","context":"macOS (Cmd+Ctrl+Q)","os":"macos"}]', 'system', 'beginner', 'macos'),
(array['meta','shift','3'], 'Screenshot Full', 'Capture the entire screen.',
  '[{"name":"Screenshot","context":"macOS (Cmd+Shift+3)","os":"macos"}]', 'system', 'beginner', 'macos'),
(array['meta','shift','4'], 'Screenshot Region', 'Capture a selected portion of the screen.',
  '[{"name":"Screenshot Region","context":"macOS (Cmd+Shift+4)","os":"macos"}]', 'system', 'beginner', 'macos'),
(array['meta','shift','5'], 'Screenshot Tools', 'Open the screenshot and screen-recording toolbar.',
  '[{"name":"Screenshot Toolbar","context":"macOS (Cmd+Shift+5)","os":"macos"}]', 'system', 'intermediate', 'macos'),
(array['ctrl','arrowup'], 'Mission Control', 'Show all open windows and Spaces.',
  '[{"name":"Mission Control","context":"macOS (Ctrl+Up)","os":"macos"}]', 'navigation', 'intermediate', 'macos'),
(array['ctrl','arrowright'], 'Next Space', 'Move to the Space on the right.',
  '[{"name":"Next Space","context":"macOS (Ctrl+Right)","os":"macos"}]', 'navigation', 'intermediate', 'macos'),
(array['meta','comma'], 'Open Preferences', 'Open the active app''s settings/preferences.',
  '[{"name":"Preferences","context":"macOS (Cmd+,)","os":"macos"}]', 'system', 'beginner', 'macos'),
(array['meta','tab','grave'], 'Cycle App Windows', 'Cycle between windows of the active app (Cmd+`).',
  '[{"name":"Cycle Windows","context":"macOS (Cmd+`)","os":"macos"}]', 'navigation', 'intermediate', 'macos'),

-- ===========================================================================
-- LINUX (GNOME / common desktop)
-- ===========================================================================
(array['ctrl','c'], 'Copy', 'Copy the selection to the clipboard.',
  '[{"name":"Copy","context":"Linux","os":"linux"}]', 'editing', 'beginner', 'linux'),
(array['ctrl','v'], 'Paste', 'Paste clipboard contents at the cursor.',
  '[{"name":"Paste","context":"Linux","os":"linux"}]', 'editing', 'beginner', 'linux'),
(array['ctrl','shift','c'], 'Copy in Terminal', 'Copy selected text in a terminal emulator.',
  '[{"name":"Copy (Terminal)","context":"Linux terminal","os":"linux"}]', 'editing', 'beginner', 'linux'),
(array['ctrl','shift','v'], 'Paste in Terminal', 'Paste into a terminal emulator.',
  '[{"name":"Paste (Terminal)","context":"Linux terminal","os":"linux"}]', 'editing', 'beginner', 'linux'),
(array['ctrl','alt','t'], 'Open Terminal', 'Launch a terminal window.',
  '[{"name":"Open Terminal","context":"Ubuntu / GNOME","os":"linux"}]', 'system', 'beginner', 'linux'),
(array['alt','tab'], 'Switch Apps', 'Cycle between open applications.',
  '[{"name":"Switch Apps","context":"Linux","os":"linux"}]', 'navigation', 'beginner', 'linux'),
(array['alt','f2'], 'Run Command', 'Open the run-a-command dialog (GNOME).',
  '[{"name":"Run Command","context":"GNOME","os":"linux"}]', 'system', 'intermediate', 'linux'),
(array['ctrl','alt','arrowright'], 'Next Workspace', 'Switch to the next workspace.',
  '[{"name":"Next Workspace","context":"Linux","os":"linux"}]', 'navigation', 'intermediate', 'linux'),
(array['ctrl','alt','del'], 'Log Out / Power', 'Open the log out or power menu (varies by DE).',
  '[{"name":"Log Out","context":"Linux","os":"linux"}]', 'system', 'beginner', 'linux'),
(array['meta'], 'Activities Overview', 'Open the Activities/search overview (GNOME).',
  '[{"name":"Activities","context":"GNOME (Super)","os":"linux"}]', 'navigation', 'beginner', 'linux'),
(array['ctrl','alt','l'], 'Lock Screen', 'Lock the screen.',
  '[{"name":"Lock","context":"GNOME","os":"linux"}]', 'system', 'beginner', 'linux'),
(array['prtsc'], 'Screenshot', 'Capture the full screen.',
  '[{"name":"Screenshot","context":"Linux (Print Screen)","os":"linux"}]', 'system', 'beginner', 'linux'),

-- ===========================================================================
-- CHROME (cross-platform; primary keys shown for Windows/Linux, Cmd noted)
-- ===========================================================================
(array['ctrl','t'], 'New Tab', 'Open a new browser tab.',
  '[{"name":"New Tab","context":"Chrome (Win/Linux)","os":"windows"},{"name":"New Tab","context":"Chrome macOS uses Cmd+T","os":"macos"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','shift','t'], 'Reopen Closed Tab', 'Reopen the most recently closed tab.',
  '[{"name":"Reopen Tab","context":"Chrome (Win/Linux)","os":"windows"},{"name":"Reopen Tab","context":"Chrome macOS uses Cmd+Shift+T","os":"macos"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','w'], 'Close Tab', 'Close the active tab.',
  '[{"name":"Close Tab","context":"Chrome (Win/Linux)","os":"windows"},{"name":"Close Tab","context":"Chrome macOS uses Cmd+W","os":"macos"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','shift','n'], 'New Incognito Window', 'Open a new private browsing window.',
  '[{"name":"Incognito","context":"Chrome (Win/Linux)","os":"windows"},{"name":"Incognito","context":"Chrome macOS uses Cmd+Shift+N","os":"macos"}]', 'browser', 'intermediate', 'chrome'),
(array['ctrl','l'], 'Focus Address Bar', 'Highlight the URL in the address bar.',
  '[{"name":"Focus Omnibox","context":"Chrome (Win/Linux)","os":"windows"},{"name":"Focus Omnibox","context":"Chrome macOS uses Cmd+L","os":"macos"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','r'], 'Reload Page', 'Reload the current page.',
  '[{"name":"Reload","context":"Chrome (Win/Linux)","os":"windows"},{"name":"Reload","context":"Chrome macOS uses Cmd+R","os":"macos"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','shift','r'], 'Hard Reload', 'Reload ignoring cached files.',
  '[{"name":"Hard Reload","context":"Chrome (Win/Linux)","os":"windows"},{"name":"Hard Reload","context":"Chrome macOS uses Cmd+Shift+R","os":"macos"}]', 'browser', 'intermediate', 'chrome'),
(array['ctrl','shift','i'], 'Open DevTools', 'Open the developer tools panel.',
  '[{"name":"DevTools","context":"Chrome (Win/Linux)","os":"windows"},{"name":"DevTools","context":"Chrome macOS uses Cmd+Option+I","os":"macos"}]', 'browser', 'advanced', 'chrome'),
(array['ctrl','shift','j'], 'Open Console', 'Open the JavaScript console.',
  '[{"name":"Console","context":"Chrome (Win/Linux)","os":"windows"}]', 'browser', 'advanced', 'chrome'),
(array['ctrl','shift','delete'], 'Clear Browsing Data', 'Open the clear browsing data dialog.',
  '[{"name":"Clear Data","context":"Chrome","os":"windows"}]', 'browser', 'intermediate', 'chrome'),
(array['ctrl','d'], 'Bookmark Page', 'Bookmark the current page.',
  '[{"name":"Bookmark","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','tab'], 'Next Tab', 'Switch to the next tab.',
  '[{"name":"Next Tab","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','shift','tab'], 'Previous Tab', 'Switch to the previous tab.',
  '[{"name":"Previous Tab","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','plus'], 'Zoom In', 'Increase the page zoom level.',
  '[{"name":"Zoom In","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','minus'], 'Zoom Out', 'Decrease the page zoom level.',
  '[{"name":"Zoom Out","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','0'], 'Reset Zoom', 'Reset the page zoom to 100%.',
  '[{"name":"Reset Zoom","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','j'], 'Open Downloads', 'Open the downloads page.',
  '[{"name":"Downloads","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),
(array['ctrl','h'], 'Open History', 'Open the browsing history page.',
  '[{"name":"History","context":"Chrome","os":"windows"}]', 'browser', 'beginner', 'chrome'),

-- ===========================================================================
-- FIREFOX
-- ===========================================================================
(array['ctrl','t'], 'New Tab', 'Open a new browser tab.',
  '[{"name":"New Tab","context":"Firefox (Win/Linux)","os":"windows"},{"name":"New Tab","context":"Firefox macOS uses Cmd+T","os":"macos"}]', 'browser', 'beginner', 'firefox'),
(array['ctrl','shift','t'], 'Reopen Closed Tab', 'Reopen the most recently closed tab.',
  '[{"name":"Reopen Tab","context":"Firefox","os":"windows"}]', 'browser', 'beginner', 'firefox'),
(array['ctrl','w'], 'Close Tab', 'Close the active tab.',
  '[{"name":"Close Tab","context":"Firefox","os":"windows"}]', 'browser', 'beginner', 'firefox'),
(array['ctrl','shift','p'], 'New Private Window', 'Open a new private browsing window.',
  '[{"name":"Private Window","context":"Firefox","os":"windows"}]', 'browser', 'intermediate', 'firefox'),
(array['ctrl','l'], 'Focus Address Bar', 'Highlight the URL in the address bar.',
  '[{"name":"Focus URL","context":"Firefox","os":"windows"}]', 'browser', 'beginner', 'firefox'),
(array['ctrl','shift','i'], 'Open DevTools', 'Open the developer tools panel.',
  '[{"name":"DevTools","context":"Firefox","os":"windows"}]', 'browser', 'advanced', 'firefox'),
(array['ctrl','shift','k'], 'Open Web Console', 'Open the Firefox web console.',
  '[{"name":"Web Console","context":"Firefox","os":"windows"}]', 'browser', 'advanced', 'firefox'),
(array['ctrl','d'], 'Bookmark Page', 'Bookmark the current page.',
  '[{"name":"Bookmark","context":"Firefox","os":"windows"}]', 'browser', 'beginner', 'firefox'),
(array['ctrl','shift','a'], 'Open Add-ons', 'Open the add-ons manager.',
  '[{"name":"Add-ons","context":"Firefox","os":"windows"}]', 'browser', 'intermediate', 'firefox'),

-- ===========================================================================
-- VS CODE
-- ===========================================================================
(array['ctrl','shift','p'], 'Command Palette', 'Open the command palette to run any command.',
  '[{"name":"Command Palette","context":"VS Code (Win/Linux)","os":"windows"},{"name":"Command Palette","context":"VS Code macOS uses Cmd+Shift+P","os":"macos"}]', 'productivity', 'beginner', 'vscode'),
(array['ctrl','p'], 'Quick Open File', 'Quickly open a file by name.',
  '[{"name":"Quick Open","context":"VS Code (Win/Linux)","os":"windows"},{"name":"Quick Open","context":"VS Code macOS uses Cmd+P","os":"macos"}]', 'navigation', 'beginner', 'vscode'),
(array['ctrl','b'], 'Toggle Sidebar', 'Show or hide the side bar.',
  '[{"name":"Toggle Sidebar","context":"VS Code","os":"windows"}]', 'navigation', 'beginner', 'vscode'),
(array['ctrl','grave'], 'Toggle Terminal', 'Show or hide the integrated terminal.',
  '[{"name":"Toggle Terminal","context":"VS Code (Ctrl+`)","os":"windows"}]', 'productivity', 'beginner', 'vscode'),
(array['ctrl','shift','f'], 'Search in Files', 'Search across all files in the workspace.',
  '[{"name":"Search Files","context":"VS Code","os":"windows"}]', 'navigation', 'beginner', 'vscode'),
(array['ctrl','d'], 'Add Next Occurrence', 'Select the next occurrence of the current word.',
  '[{"name":"Multi-cursor","context":"VS Code","os":"windows"}]', 'editing', 'intermediate', 'vscode'),
(array['alt','arrowup'], 'Move Line Up', 'Move the current line up.',
  '[{"name":"Move Line Up","context":"VS Code","os":"windows"}]', 'editing', 'intermediate', 'vscode'),
(array['alt','arrowdown'], 'Move Line Down', 'Move the current line down.',
  '[{"name":"Move Line Down","context":"VS Code","os":"windows"}]', 'editing', 'intermediate', 'vscode'),
(array['shift','alt','arrowdown'], 'Copy Line Down', 'Duplicate the current line below.',
  '[{"name":"Copy Line Down","context":"VS Code","os":"windows"}]', 'editing', 'intermediate', 'vscode'),
(array['ctrl','slash'], 'Toggle Line Comment', 'Comment or uncomment the current line.',
  '[{"name":"Toggle Comment","context":"VS Code","os":"windows"}]', 'editing', 'beginner', 'vscode'),
(array['ctrl','shift','k'], 'Delete Line', 'Delete the current line.',
  '[{"name":"Delete Line","context":"VS Code","os":"windows"}]', 'editing', 'intermediate', 'vscode'),
(array['ctrl','g'], 'Go to Line', 'Jump to a specific line number.',
  '[{"name":"Go to Line","context":"VS Code","os":"windows"}]', 'navigation', 'beginner', 'vscode'),
(array['f2'], 'Rename Symbol', 'Rename a symbol across the project.',
  '[{"name":"Rename Symbol","context":"VS Code","os":"windows"}]', 'editing', 'intermediate', 'vscode'),
(array['f12'], 'Go to Definition', 'Jump to the definition of a symbol.',
  '[{"name":"Go to Definition","context":"VS Code","os":"windows"}]', 'navigation', 'intermediate', 'vscode'),
(array['ctrl','shift','e'], 'Show Explorer', 'Focus the file explorer.',
  '[{"name":"Explorer","context":"VS Code","os":"windows"}]', 'navigation', 'beginner', 'vscode'),
(array['ctrl','shift','x'], 'Show Extensions', 'Open the extensions view.',
  '[{"name":"Extensions","context":"VS Code","os":"windows"}]', 'productivity', 'beginner', 'vscode'),
(array['ctrl','k','ctrl','s'], 'Keyboard Shortcuts', 'Open the keyboard shortcuts editor.',
  '[{"name":"Shortcuts","context":"VS Code","os":"windows"}]', 'productivity', 'advanced', 'vscode'),

-- ===========================================================================
-- EXCEL
-- ===========================================================================
(array['ctrl','c'], 'Copy', 'Copy the selected cells.',
  '[{"name":"Copy","context":"Excel","os":"windows"}]', 'editing', 'beginner', 'excel'),
(array['ctrl','v'], 'Paste', 'Paste copied cells.',
  '[{"name":"Paste","context":"Excel","os":"windows"}]', 'editing', 'beginner', 'excel'),
(array['ctrl','shift','v'], 'Paste Special', 'Open the Paste Special dialog.',
  '[{"name":"Paste Special","context":"Excel","os":"windows"}]', 'editing', 'intermediate', 'excel'),
(array['ctrl','z'], 'Undo', 'Undo the last action.',
  '[{"name":"Undo","context":"Excel","os":"windows"}]', 'editing', 'beginner', 'excel'),
(array['ctrl','arrowdown'], 'Jump to Edge', 'Jump to the bottom edge of the data region.',
  '[{"name":"Edge Navigation","context":"Excel","os":"windows"}]', 'navigation', 'intermediate', 'excel'),
(array['ctrl','shift','arrowdown'], 'Select to Edge', 'Select cells to the edge of the data region.',
  '[{"name":"Select to Edge","context":"Excel","os":"windows"}]', 'navigation', 'intermediate', 'excel'),
(array['alt','=' ], 'AutoSum', 'Insert a SUM formula for adjacent cells.',
  '[{"name":"AutoSum","context":"Excel (Alt+=)","os":"windows"}]', 'productivity', 'intermediate', 'excel'),
(array['ctrl','shift','l'], 'Toggle Filter', 'Turn AutoFilter on or off.',
  '[{"name":"Filter","context":"Excel","os":"windows"}]', 'productivity', 'intermediate', 'excel'),
(array['ctrl','t'], 'Create Table', 'Convert a range into a table.',
  '[{"name":"Create Table","context":"Excel","os":"windows"}]', 'productivity', 'intermediate', 'excel'),
(array['ctrl','1'], 'Format Cells', 'Open the Format Cells dialog.',
  '[{"name":"Format Cells","context":"Excel","os":"windows"}]', 'editing', 'intermediate', 'excel'),
(array['ctrl','shift','plus'], 'Insert Cells', 'Insert new cells, rows, or columns.',
  '[{"name":"Insert","context":"Excel","os":"windows"}]', 'editing', 'intermediate', 'excel'),
(array['ctrl','semicolon'], 'Insert Date', 'Insert the current date.',
  '[{"name":"Insert Date","context":"Excel","os":"windows"}]', 'productivity', 'beginner', 'excel'),
(array['f4'], 'Toggle Reference', 'Cycle absolute/relative cell references in a formula.',
  '[{"name":"Toggle $ Reference","context":"Excel","os":"windows"}]', 'editing', 'advanced', 'excel'),
(array['ctrl','pageup'], 'Previous Sheet', 'Move to the previous worksheet.',
  '[{"name":"Previous Sheet","context":"Excel","os":"windows"}]', 'navigation', 'beginner', 'excel'),
(array['ctrl','pagedown'], 'Next Sheet', 'Move to the next worksheet.',
  '[{"name":"Next Sheet","context":"Excel","os":"windows"}]', 'navigation', 'beginner', 'excel'),

-- ===========================================================================
-- WORD
-- ===========================================================================
(array['ctrl','b'], 'Bold', 'Toggle bold formatting on the selection.',
  '[{"name":"Bold","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),
(array['ctrl','i'], 'Italic', 'Toggle italic formatting on the selection.',
  '[{"name":"Italic","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),
(array['ctrl','u'], 'Underline', 'Toggle underline formatting on the selection.',
  '[{"name":"Underline","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),
(array['ctrl','e'], 'Center Align', 'Center-align the current paragraph.',
  '[{"name":"Center","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),
(array['ctrl','l'], 'Left Align', 'Left-align the current paragraph.',
  '[{"name":"Left Align","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),
(array['ctrl','r'], 'Right Align', 'Right-align the current paragraph.',
  '[{"name":"Right Align","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),
(array['ctrl','j'], 'Justify', 'Justify the current paragraph.',
  '[{"name":"Justify","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),
(array['ctrl','shift','c'], 'Copy Formatting', 'Copy formatting from the selection.',
  '[{"name":"Copy Format","context":"Word","os":"windows"}]', 'editing', 'intermediate', 'word'),
(array['ctrl','shift','v'], 'Paste Formatting', 'Apply copied formatting to the selection.',
  '[{"name":"Paste Format","context":"Word","os":"windows"}]', 'editing', 'intermediate', 'word'),
(array['ctrl','k'], 'Insert Hyperlink', 'Insert or edit a hyperlink.',
  '[{"name":"Hyperlink","context":"Word","os":"windows"}]', 'productivity', 'intermediate', 'word'),
(array['ctrl','enter'], 'Page Break', 'Insert a page break at the cursor.',
  '[{"name":"Page Break","context":"Word","os":"windows"}]', 'editing', 'intermediate', 'word'),
(array['ctrl','shift','n'], 'Apply Normal Style', 'Apply the Normal paragraph style.',
  '[{"name":"Normal Style","context":"Word","os":"windows"}]', 'editing', 'intermediate', 'word'),
(array['shift','f3'], 'Change Case', 'Cycle the case of the selected text.',
  '[{"name":"Change Case","context":"Word","os":"windows"}]', 'editing', 'intermediate', 'word'),
(array['ctrl','shift','greater'], 'Grow Font', 'Increase the font size of the selection.',
  '[{"name":"Grow Font","context":"Word","os":"windows"}]', 'editing', 'beginner', 'word'),

-- ===========================================================================
-- FIGMA
-- ===========================================================================
(array['v'], 'Move Tool', 'Activate the move/selection tool.',
  '[{"name":"Move Tool","context":"Figma","os":"windows"}]', 'editing', 'beginner', 'figma'),
(array['f'], 'Frame Tool', 'Activate the frame tool.',
  '[{"name":"Frame Tool","context":"Figma","os":"windows"}]', 'editing', 'beginner', 'figma'),
(array['r'], 'Rectangle', 'Draw a rectangle.',
  '[{"name":"Rectangle","context":"Figma","os":"windows"}]', 'editing', 'beginner', 'figma'),
(array['t'], 'Text Tool', 'Activate the text tool.',
  '[{"name":"Text Tool","context":"Figma","os":"windows"}]', 'editing', 'beginner', 'figma'),
(array['p'], 'Pen Tool', 'Activate the pen tool for vector paths.',
  '[{"name":"Pen Tool","context":"Figma","os":"windows"}]', 'editing', 'intermediate', 'figma'),
(array['ctrl','g'], 'Group Selection', 'Group the selected layers.',
  '[{"name":"Group","context":"Figma (Win)","os":"windows"},{"name":"Group","context":"Figma macOS uses Cmd+G","os":"macos"}]', 'editing', 'beginner', 'figma'),
(array['ctrl','shift','g'], 'Ungroup Selection', 'Ungroup the selected group.',
  '[{"name":"Ungroup","context":"Figma (Win)","os":"windows"},{"name":"Ungroup","context":"Figma macOS uses Cmd+Shift+G","os":"macos"}]', 'editing', 'beginner', 'figma'),
(array['ctrl','alt','k'], 'Create Component', 'Turn the selection into a component.',
  '[{"name":"Create Component","context":"Figma","os":"windows"}]', 'productivity', 'advanced', 'figma'),
(array['ctrl','d'], 'Duplicate', 'Duplicate the selected layers.',
  '[{"name":"Duplicate","context":"Figma","os":"windows"}]', 'editing', 'beginner', 'figma'),
(array['shift','a'], 'Auto Layout', 'Add auto layout to the selection.',
  '[{"name":"Auto Layout","context":"Figma","os":"windows"}]', 'productivity', 'advanced', 'figma'),
(array['ctrl','shift','k'], 'Place Image', 'Import and place an image.',
  '[{"name":"Place Image","context":"Figma","os":"windows"}]', 'productivity', 'intermediate', 'figma'),
(array['shift','2'], 'Zoom to Selection', 'Zoom the canvas to fit the selection.',
  '[{"name":"Zoom to Selection","context":"Figma","os":"windows"}]', 'navigation', 'beginner', 'figma'),
(array['alt'], 'Measure Distance', 'Hold to measure distance between objects.',
  '[{"name":"Measure","context":"Figma (hold Alt)","os":"windows"}]', 'navigation', 'intermediate', 'figma')

on conflict (name, app) do update set
  keys        = excluded.keys,
  description = excluded.description,
  platforms   = excluded.platforms,
  category    = excluded.category,
  difficulty  = excluded.difficulty;

-- ===========================================================================
-- Adding MORE apps (PowerPoint, Slack, Photoshop, Notion, Gmail, etc.)
-- ===========================================================================
-- The `app` column is constrained to 9 values. To add a new app you must:
--
-- 1) Extend the AppId union in lib/types.ts, e.g.:
--      | "powerpoint" | "slack" | "photoshop"
--
-- 2) Widen the DB CHECK constraint (run once in the SQL Editor):
--      alter table public.shortcuts drop constraint shortcuts_app_check;
--      alter table public.shortcuts add constraint shortcuts_app_check
--        check (app in (
--          'windows','macos','linux','chrome','firefox','vscode',
--          'excel','word','figma',
--          'powerpoint','slack','photoshop'   -- new values
--        ));
--
-- 3) Then INSERT rows with the new app value just like the blocks above.
